### ISSUE TITLE
'Side-Image' short code not 'installed' or not working

### ISSUE THREAD

**Issue by thisisjoewells** [TheDetroitZoo/polk-penguin-center-child-theme#2]
Hi.
The handy-dandy shortcode 'side-image' for making nice consistent content blocks is not working.

It is one of the two short-codes that are available on the content editor, but when you select it the box is empty.

I copy/pasted some code from live DZ site to see what happens.  The site/theme just doesn't know how to handle it:

![polk-microsite-side-image-shortcode-no-go](https://cloud.githubusercontent.com/assets/9747248/13017790/529a8c5c-d194-11e5-8a97-3047d9c32052.jpg)

I bet the same is the case on Sunset/DZS-Microsite-Theme.

**Comment by joelworsham** [comment]
Ahhh. It seems that some shortcodes did not get "transferred". I'll make sure they're all in there.

**Comment by joelworsham** [comment]
This issue was moved to TheDetroitZoo/dzs-microsite-1#33
