### ISSUE TITLE
Minor Detail - should not use 'ppcc' for anything...

### ISSUE THREAD

**Issue by thisisjoewells** [TheDetroitZoo/polk-penguin-center-child-theme#3]
Hi.
Does it matter that I renamed the title of the repo "polk-penguin-center-child-theme" and the child theme folder penguin-center?

We have strict instructions from PR/Comm not to use abbreviations 'PPCC' or 'P2C2', because it is important to call it 'Polk Penguin Conservation Center' and 'Penguin Center' on 2nd mention.  I know this is inside....but this repo is not private like others...I figure I'll keep us more compliant...

**Comment by joelworsham** [comment]
Ha okay. The only issue is that you probably have lost theme-dependant settings (widgets, menus, customizer settings). I can migrate that if you like. Have you already changed the name and switched over? And on production or staging or both?

**Comment by thisisjoewells** [comment]
All I did was change the name/description in some files on Development branch.  Then also changed folder name on staging.  Mostly to see what happens :)  Looks to be fine.

It seems to have kept all the customizer settings on staging - http://penguins-detroitzoo-org.dzs2.staging.wpengine.com/

We are still going to be making major changes to it, not so much code, but graphic files as we are able to get into the center and take real photos.  So we don't need to migrate settings to live yet, right?

You can do that before launch, or perhaps even just talk me through the process.  We'll see I guess.

Is it a good plan to just merge Development changes into Master?  It's just descriptions.

**Comment by joelworsham** [comment]
Welp, I went to the themes page to check, and got an error saying the theme no longer exists and it reverted to 2016. This is what I anticipated. WordPress identifies themes and plugins by the directory name.

I've re-selected it and migrated the theme settings.

**Comment by thisisjoewells** [comment]
So it all seems good to go.
